# Generated by Django 5.0.3 on 2024-04-16 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accounts_no', models.IntegerField()),
                ('accounts_type', models.CharField()),
                ('From_past', models.CharField(blank=True)),
                ('create_datetime', models.DateTimeField()),
                ('update_datetime', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='user_address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_type', models.CharField()),
                ('address1', models.CharField()),
                ('address2', models.CharField()),
                ('city', models.CharField()),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField()),
                ('country', models.CharField()),
                ('create_datetime', models.DateTimeField()),
                ('update_datetime', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
        ),
    ]
