# Generated by Django 5.0.3 on 2024-04-16 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_accounts_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='transcations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_accounts_id', models.IntegerField()),
                ('txn_type', models.CharField()),
                ('status', models.CharField()),
                ('create_datetime', models.DateTimeField()),
                ('update_datetime', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
        ),
    ]
