# Generated by Django 5.0.3 on 2024-06-21 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_transcations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_accounts',
            old_name='accounts_no',
            new_name='user_accounts_no',
        ),
        migrations.RenameField(
            model_name='user_accounts',
            old_name='accounts_type',
            new_name='user_accounts_type',
        ),
        migrations.AlterField(
            model_name='user_accounts',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_accounts',
            name='update_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='address1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='address2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='User_transcations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_accounts_id', models.IntegerField()),
                ('txn_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='User_transfers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now_add=True)),
                ('user_accounts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_transcations')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='User_recipients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_account_no', models.IntegerField()),
                ('user_accounttype', models.CharField(max_length=1000)),
                ('transfer_type', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=100)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_transfers')),
            ],
        ),
        migrations.DeleteModel(
            name='transcations',
        ),
    ]
