# Generated by Django 5.0.6 on 2024-06-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_accounts_no_user_accounts_user_accounts_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_transcations',
            name='amount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
