# Generated by Django 5.0.6 on 2024-06-24 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_transcations_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_address',
            new_name='address',
        ),
        migrations.RenameModel(
            old_name='User_transfers',
            new_name='transfers',
        ),
        migrations.RenameModel(
            old_name='UserRegistration',
            new_name='User',
        ),
        migrations.CreateModel(
            name='transcations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_accounts_id', models.IntegerField()),
                ('txn_type', models.CharField(max_length=100)),
                ('amount', models.FloatField(default='')),
                ('status', models.CharField(max_length=100)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AlterField(
            model_name='transfers',
            name='user_accounts_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.transcations'),
        ),
        migrations.DeleteModel(
            name='User_transcations',
        ),
    ]
