# Generated by Django 5.0.6 on 2024-06-25 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_user_address_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_recipients',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
