# Generated by Django 5.0.6 on 2024-06-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_email_user_email_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_accounts',
            name='From_past',
        ),
    ]
