# Generated by Django 5.0.6 on 2024-06-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_accounts_from_past'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user_accounts',
            old_name='user_accounts_no',
            new_name='accounts_no',
        ),
        migrations.RenameField(
            model_name='user_accounts',
            old_name='user_accounts_type',
            new_name='accounts_type',
        ),
        migrations.RenameField(
            model_name='user_recipients',
            old_name='user_account_no',
            new_name='account_no',
        ),
        migrations.RenameField(
            model_name='user_recipients',
            old_name='user_accounttype',
            new_name='accounttype',
        ),
        migrations.AddField(
            model_name='user_accounts',
            name='FromPast',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transcations',
            name='user_accounts_id',
            field=models.CharField(max_length=100),
        ),
    ]
