# Generated by Django 5.0.6 on 2024-06-26 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_user_id_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcations',
            name='user_accounts_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_accounts'),
        ),
    ]
