# Generated by Django 5.0.6 on 2024-06-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_transcations_user_accounts_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transcations',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transfers',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_accounts',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_recipients',
            old_name='user_id',
            new_name='user',
        ),
    ]
