# Generated by Django 5.0.6 on 2024-06-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_user_id_address_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcations',
            old_name='user_accounts_id',
            new_name='user_accounts',
        ),
        migrations.RenameField(
            model_name='transfers',
            old_name='recipient_id',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='transfers',
            old_name='user_accounts_id',
            new_name='user_accounts',
        ),
    ]
