# Generated by Django 5.0.6 on 2024-07-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_transcations_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
