# Generated by Django 5.0.6 on 2024-07-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_create_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_recipients',
            name='accounttype',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
