# Generated by Django 5.0.6 on 2024-07-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_recipients_accounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user_recipients',
            name='accounttype',
            field=models.CharField(default=False, max_length=1000),
        ),
    ]
